### ISSUE TITLE
Bernoulli mixed model calling `std` function with non-existing kwarg `normalize`

### ISSUE THREAD

**Issue by Cong-SUN** [TuringLang/TuringGLM.jl#149]
in TuringGLM/0rvqL/src/turing_model.jl:266 it uses std(y; normalize=true), but this function actually doesn't accept normalize as a kwarg: std(x::AbstractArray, w::AbstractWeights, [dim]; mean=nothing, corrected=false).

**Comment by penelopeysm** [comment]
https://github.com/TuringLang/TuringGLM.jl/blob/7f2a849151e103356facdca9a0668ff1ae30c2cd/src/turing_model.jl#L266

**Comment by rikhuijzer** [comment]
> in TuringGLM/0rvqL/src/turing_model.jl:266 it uses std(y; normalize=true), but this function actually doesn't accept normalize as a kwarg: std(x::AbstractArray, w::AbstractWeights, [dim]; mean=nothing, corrected=false).

Thanks for reporting this @Cong-SUN. Do you have a reproducible example? What model did you run to get this error?
