### ISSUE TITLE
Slightly Broader Name?

### ISSUE THREAD

**Issue by ParadaCarleton** [TuringLang/TuringGLM.jl#16]
Might be worth it to give a broader name than TuringGLM in case we want to expand a bit past GLMs. For instance, being able to specify a generalized additive model where some components are estimated with a Gaussian process regression would be a very neat feature.

**Comment by phipsgabler** [comment]
I have to say I have wondered about this as well. The Stan equivalent is [rstanarm](http://mc-stan.org/rstanarm/), "advanced regression modelling" if I'm not mistaken -- TuringAdvancedRegressionModelling?

**Comment by storopoli** [comment]
What acronym or names do you guys suggest?

**Comment by phipsgabler** [comment]
JuTurArm? :laughing: 

Seriously, I don't really have any perfect options myself. TuringARM would likely run afoul of the package naming guidelines. Maybe just TuringRegressionModels? Anyway, I don't want to strongly push anything here, it's really your choice.

**Comment by storopoli** [comment]
TuringRegressionModels is a good name but also huge.

**Comment by cpfiffer** [comment]
It should probably be short -- TuringGLM gets the point across moderately well, but I agree with Carlos that it falls short of the potential in here. TuringRegression is a good candidate IMO, could also suggest TuringClustering or other common modelling framework names.

**Comment by ParadaCarleton** [comment]
Simple Modeling or Regression with Turing: SMORT

(Yes, I did fill this in as a backronym after thinking it would be funny to have a package named SMORT)

**Comment by cpfiffer** [comment]
> Simple Modeling or Regression with Turing: SMORT
> 
> (Yes, I did fill this in as a backronym after thinking it would be funny to have a package named SMORT)

Lol I appreciate the vigor but it's a downvote from me.

**Comment by ParadaCarleton** [comment]
Understandable, have a nice day

**Comment by storopoli** [comment]
We should either have a reference from a Julia ecosystem package (this is why I used the `*GLM.jl`) or from Bayesian modeling in other languages (`brms` or `rstanarm`, but please no `bambi`).

**Comment by rikhuijzer** [comment]
TuringGLM is being registered currently.
