### ISSUE TITLE
Feature list for 0.1.0 release

### ISSUE THREAD

**Issue by storopoli** [TuringLang/TuringGLM.jl#2]
- [x] `turing_model` function:
  ```julia
  turing_model(formula, data;
        family=Normal,
        priors=DefaultPriors(),
        standardize=false)
  ```
- [x] Close interface with `DataFrames.jl` and `CategoricalArrays.jl` using the `Tables.jl` API:
  - [x] Reading the `length(unique(x))` of a group-level intercept/slope
  - [x] Auto dummy variable ($K - 1$) with `categorical` vectors by reading the `levels` and using the first level as baseline.
- [x] Likelihoods:
  - [x] Linear Regression: `Gaussian` and `TDist` (`IdentityLink`)
  - [x] Logistic Regression: `Bernoulli`
  - [x] Count Data: `Poisson` and `NegativeBinomial` (`LogLink`)
- [x] Priors:
  - [x] Default Priors and Custom Priors
- [x] Group-level effects (Hierarchical Models):
  - [x] Non-Centered Parameterization and recompute the parameter back in the `return` statement
  - [x] Varying-Intercept: `(1 | group)`
- [x] Case Studies showcasing: 
  - [x] `@formula` syntax
  - [x] random effects: random-intercept
  - [x] likelihoods
  - [x] `CategoricalArrays.jl` and `DataFrames.jl` (`Tables.jl`) interfaces
  - [x] Use the `{rstanarm}` datasets (check LICENSE) and the `sleep` dataset from `{brms}`

**Comment by phipsgabler** [comment]
One of these models embedded as a `@submodel` in another Turing model would be a cool show case and interaction test, I think.

**Comment by storopoli** [comment]
Thanks, do you have good resources on `@submodel`. I want o learn more about it, never used.

**Comment by phipsgabler** [comment]
They are unfortunately not at all documented, but [the PR](https://github.com/TuringLang/DynamicPPL.jl/pull/233) should cover the usage.
