### ISSUE TITLE
Getting more numerical errors when setting `standardize=true`

### ISSUE THREAD

**Issue by rikhuijzer** [TuringLang/TuringGLM.jl#37]
With an unstandardized dataset and `standardize=false` (the default), I got 3 numerical errors on a `Logistic` model. With `standardize=true`, I got hundreds of numerical errors. This shouldn't happen, right? With standardization, the sampler already starts roughly in the right place meaning that less numerical errors should occur.

**Comment by storopoli** [comment]
Is this during warmup or sampling?
