### ISSUE TITLE
use intercept traits w/ `apply_schema` to handle implicit intercept

### ISSUE THREAD

**Issue by kleinschmidt** [TuringLang/TuringGLM.jl#39]
StatsModels provides the notion of "intercept traits" https://github.com/JuliaStats/StatsModels.jl/blob/master/src/traits.jl to control the behavior of the automatic intercept adding that normally happens in GLMs.  This package is a great example of a model type with an ~~"implicit intercept"~~ "dropped intercept", since everything is centered (AFAICT) so the intercept is always zero and shouldn't be included.

I think what you'd want to do is to define a model type (if there isn't one already) and add methods for the appropriate types.

**Comment by storopoli** [comment]
I am trying to have the least middleware possible between `@formula` and `Turing.jl`.
What would be the added benefits?

**Comment by phipsgabler** [comment]
In principle, you can dispatch on DPPL models since a couple of months (the purpose of which was exactly to be able to define traits):

```julia
julia> @model function m1()
           d ~ filldist(DiscreteUniform(1, 3), 3)
           return d
       end
m1 (generic function with 2 methods)

julia> trait(::Model{typeof(m1)}) = true
trait (generic function with 1 method)

julia> trait(m1())
true
```

You'd only need to move the closures out of `turing_model` to get access to the function.

**Comment by storopoli** [comment]
We currently don't implement/extend the `StatisticalModel` type from `StatsModels.jl`.
So I think that the traits are to be applied to those types.
I am closing this, we might revisit this in the future if we need to use `StatisticalModel`.
