### ISSUE TITLE
Docs `index.md` broken?

### ISSUE THREAD

**Issue by Moelf** [TuringLang/TuringGLM.jl#56]
![image](https://user-images.githubusercontent.com/5306213/173663801-65b6c1c7-96eb-48fe-a6e1-d4f55a873611.png)

**Comment by rikhuijzer** [comment]
The : probably refers to the Linear Regression at the right bottom, but I agree that it could be improved. PR’s are welcome

**Comment by Moelf** [comment]
we have tutorials links in the left bar I feel like this is kinda redundant, maybe just link to that page instead of the `depth = 1`

**Comment by storopoli** [comment]
I think that is fixed in `stable`: https://beta.turing.ml/TuringGLM.jl/stable/
Feel free to reopen this issue if I am mistaken.
